from app.core.database import Base
from app.models.user import User
from app.models.document import Document
from app.models.land_record import LandRecord
from app.models.mutation_event import MutationEvent
from app.models.ocr_feedback import OCRFeedback
from app.models.fraud_flag import FraudFlag
from app.models.court_case import CourtCase
from app.models.govt_land_record import GovtLandRecord
